name = "bppinstaller-update-check"
main = "src/index.ts"
compatibility_date = "2026-03-28"
workers_dev = false

[vars]
RELEASE_KEY = "installer:release:stable"

[[kv_namespaces]]
binding = "RELEASES"
id = "2831309e71134d1f82ae1e34a38c9aba"

[[d1_databases]]
binding = "ACTIVITY_DB"
database_name = "bppinstaller-install-clients"
database_id = "d4687f2e-d5c5-4c74-b374-10b8d324fcd3"

[[routes]]
pattern = "update-check.bazaarplusplus.com"
custom_domain = true
